### ISSUE TITLE
How to change the "role_width, requests" about Probelm Class?

### ISSUE THREAD

**Issue by kunyaoli** [bornabr/cutting-stock-problem-simulated-annealing#1]

**Comment by kunyaoli** [comment]
In my problem,there are 100 steel pipes of 10m length, which need to be cut into 30 pipes of 3.4m, 40 pipes of 4.1m and 50 pipes of 5.2m.  But, I don't konw how to input the data?

**Comment by bornabr** [comment]
As you can see in test cases written in the notebook, you should create two inputs, one for the stock length and one for your requests. Then you make an instance of the `Problem` class and then run the `simulated_annealing` with appropriate hyperparameters.

```python
Stock_Length = 10
Requests = 30 * [3.4] + 40 * [4.1] + 50 * [5.2]

problem = Problem(Stock_Length, Requests)
scores = simulated_annealing(problem, n_iterations, temp)
```
